import { ApolloWrapper } from "@/components/lib/apolloclient";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });
// import GraphQLProvider from '@/lib/provider';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleOAuthProvider clientId={process.env.NEXT_GOOGLE || ""}>
          <ApolloWrapper>
            <Header />

            {/* <GraphQLProvider> */}
            {children}
            {/* </GraphQLProvider> */}
          </ApolloWrapper>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
